jdpartsmx/jdpartsmx/apps/catalogo/urls.py
from django.conf.urls import patterns, url
from django.views import generic
from jdpartsmx.apps.catalogo import views

urlpatterns = patterns('',
    (r'^articulos/$', views.articulos_view),
    (r'^articulos/(?P<clave>[a-zA-Z0-9_-]+)/', views.articulos_view),
)

jdpartsmx/jdpartsmx/apps/catalogo/models.py
from django.db import models

class Articulo(models.Model):
    clave = models.CharField(max_length=20)
    nombre = models.CharField(max_length=100, blank=True, null=True,)
    precio = models.DecimalField(max_digits=18, decimal_places=2)
    imagen = models.ImageField(blank=True, null=True, upload_to='articulos')
    
    def __unicode__(self):
        return u'%s' % self.nombre

jdpartsmx/jdpartsmx/apps/catalogo/forms.py
#encoding:utf-8
from django import forms
from models import *
import autocomplete_light

class filtroarticulos_form(forms.Form):
    clave   = forms.CharField(max_length=100,  widget=forms.TextInput(attrs={'class':'input-small', 'placeholder':'Clave...'}),required=False)
    nombre  = forms.CharField(max_length=100,  widget=forms.TextInput(attrs={'class':'input-small', 'placeholder':'Nombre...'}),required=False)
    # articulo = forms.ModelChoiceField(required= False, queryset=Articulo.objects.all().order_by('nombre'),
    #     widget=autocomplete_light.ChoiceWidget('ArticulosAutocomplete'))

jdpartsmx/jdpartsmx/apps/catalogo/views.py
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext

#Paginacion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# user autentication
from django.contrib.auth.decorators import login_required, permission_required

from models import *
from forms import *

def index_view(request, template_name='index.html'):
    return render_to_response(template_name, {}, context_instance=RequestContext(request))
    
def articulos_view(request, clave='', template_name='/catalogo/articulos.html'):
    if request.method =='POST':    
        filtro_form = filtroarticulos_form(request.POST)
        if filtro_form.is_valid():
            clave = filtro_form.cleaned_data['clave']
            nombre = filtro_form.cleaned_data['nombre']
            if clave != '':
                articulos_list = Articulo.objects.filter(clave__icontains=clave).order_by('-nombre')
            elif nombre != '':
                articulos_list = Articulo.objects.filter(nombre__icontains=nombre).order_by('-nombre')
            else:
                articulos_list = Articulo.objects.all().order_by('-id')
    else:
        filtro_form = filtroarticulos_form()
        if clave != '':
            articulos_list = Articulo.objects.filter(clave__icontains=clave).order_by('-nombre')
            filtro_form.clave = clave
        else:
            articulos_list = Articulo.objects.all().order_by('-id')
        filtro_form = filtroarticulos_form()

    paginator = Paginator(articulos_list, 30) # Muestra 5 inventarios por pagina
    page = request.GET.get('page')

    #####PARA PAGINACION##############
    try:
        articulos = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        articulos = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        articulos = paginator.page(paginator.num_pages)

    c = {'articulos':articulos, 'filtro_form':filtro_form,}
    return render_to_response(template_name, c, context_instance=RequestContext(request))

jdpartsmx/jdpartsmx/apps/catalogo/templates/base.html
{% load dajaxice_templatetags %}
<!DOCTYPE html>
<html lang='es'>
<head>
  <meta charset='utf-8'>
  <title>jdpasrts mx</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

  <!-- Estilos -->
  <link rel='stylesheet' href='{{STATIC_URL}}css/bootstrap.css'/>
  <link rel='stylesheet' href='{{STATIC_URL}}css/base.css'/>
  <link href='http://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Oswald|Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>
  {% block style_css %}{% endblock %}

  <!-- <link rel='shortcut icon' href='{{STATIC_URL}}img/logo.png'> -->

  <script src="{{STATIC_URL}}js/jquery.min.js" ></script>
  <script src='{{STATIC_URL}}js/bootstrap.js' ></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('#clave').focus();
    $('#clave').live('keydown', function(e) { 
      var keyCode = e.keyCode || e.which; 
      if (keyCode == 13)
      {
        window.location.href = '/catalogo/articulos/'+ $('#clave').val()+'/';
      } 
    });

    $("#buscar_clave").on("click",function(){
       window.location.href = '/catalogo/articulos/'+ $('#clave').val()+'/';
    });
  });

  
  </script>
  
  {% block js_code %}

  {% endblock %}
  
  

  {% dajaxice_js_import %}
</head>
<body>

  <header>
    <div id="navbar-example" class="navbar navbar-static">
              <div class="navbar-inner" style="background-image: linear-gradient(to bottom, #FFFFFF, #FFFFFF)">
                <div class="container" style="width: auto;">
                  <a class="brand" href="/">JD Parts MX</a>
                  <ul class="nav" role="navigation">
                    <li class="dropdown">
                      <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Catalogos <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="/catalogo/articulos/">JD Parts MX</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="http://jdpc.deere.com/jdpc/servlet/com.deere.u90490.partscatalog.view.servlets.HomePageServlet_Alt" target="_blank">John Deere</a></li>
                      </ul>
                    </li>
                    <li class="dropdown">
                      <a href="#" id="drop2" role="button" class="dropdown-toggle" data-toggle="dropdown">Contacto <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop2">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Quienes somos</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Ubicacion</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Informacion</a></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Empresa</a></li>
                      </ul>
                    </li>
                  </ul>
                  <ul class="nav">
                    <input class='span input-small' id='clave' style="margin-top: 0.5em;" type='text' placeholder='Clave...' />
                    <a class="btn" id='buscar_clave' style="margin-top: -0.5em;"><i class='icon-search'></i> </a>
                  </ul>
                  <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">Jesus Manuel <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Configuracion</a></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Cerrar Sesion</a></li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div> 
    
  </header>
  
  <section class='content' style='clear:both;'>
    <div class="pagecontent">
      {% block content %}{% endblock %}
    </div>
  </section>
  <footer style="background-color: rgb(157, 168, 157);"> 
    <br>
    <div class="row-fluid text-left">
      <div class="span3 offset1">
        <strong> QUIENES SOMOS</strong>
          <br>
          <br>
          <p >
            Somos una empresa de clase mundial dedicada a la venta y compra de refacciones y partes para todo tipo de equipo y maquinaria John Deere® agrícola e industrial.
          </p>
      </div>
      <div class="span4">
        <strong>CONTACTO </strong>
        <br>
        <br>
        <address>
          <abbr title="Telefono">Tel:</abbr> (123) 456-7890<br>
          <a href="mailto:#">ventas@jdparts.com.mx</a>
        </address>
      </div>
      <div class="span3">
        <p class="text-right">
          <img src="{{STATIC_URL}}img/jdpartsmx.png" style="height: 60px; width: 145px;">
          <br>
          jdparts.com.mx &copy; 2013
        </p>
      </div>
    </div>
    
  </footer>
</body>
</html>

jdpartsmx/jdpartsmx/apps/catalogo/templates/catalogo/articulos.html
{% extends "base.html" %}
{% block js_code %}
  <script type="text/javascript">
  $('#id_clave').focus();
  </script>
{% endblock %}
{% block content %}
	
<div class="ms-custom-form container-fluid" style=" height: 2em; ">
  <div class="row-fluid">
      <div class="span2"><h3>Articulos</h3></div>
    <div class='span9' style=" margin-top: 1em; "> 
      
      <form method="post" class="form-inline" action="" enctype='multipart/form-data'>
        {% csrf_token %}  
        {{ filtro_form.articulo }}
        {{ filtro_form.clave }}{{ filtro_form.nombre }}
        <button class="btn" type="submit"><i class='icon-search'></i> </button>
      </form>   
    </div>
  </div>
</div>
<div class="pagination pagination-mini mainmenu" style=" margin-bottom: 0px; ">
  <ul>
    {% if articulos.has_previous %}
    <li><a href="?page={{ articulos.previous_page_number }}">Anterior</a></li>
    {% else %}
    <li class="disabled"><a href="#">Anterior</a></li>
    {% endif %}
    <li class="disabled"><a href="#">Pagina {{ articulos.number }} de {{ articulos.paginator.num_pages }}.</a></li>
    {% if articulos.has_next %}
    <li><a href="?page={{ articulos.next_page_number }}">Siguiente</a></li>
    {% else %}
    <li class="disabled"><a href="#">Siguiente</a></li>
    {% endif %} 
  </ul>
</div>
  <ul class="inline">
  	{% for articulo in articulos %}
    <li>
      <div class="row">
        <div class= 'span'>
          {% if articulo.imagen %}
            <img src='{{MEDIA_URL}}{{articulo.imagen}}' style="height: 75px; width: 50px; margin-top:.5em; margin-right:.5em; margin-bottom:.5em;"  class="align-left img-rounded"/>
          {% else %}
            <img src='{{MEDIA_URL}}/articulos/no-image.png' style="height: 75px; width: 50px; margin-top:.5em; margin-right:.5em; margin-bottom:.5em;"  class="align-left img-rounded"/>
          {% endif %}
        </div>
        <div class= 'span2'>
          <strong>{{ articulo.clave }}</strong> <br>
          {{ articulo.nombre }} <br><br>
          <div class="pull-right"><label class="text-info">$ {{ articulo.precio }}</label></div>
        </div>
      </div>      
    </li>
  	{% endfor %}
  </ul>
{% endblock %}

jdpartsmx/jdpartsmx/apps/catalogo/templates/index.html
{% extends "base.html" %}

{% block js_code %}
  <script src='{{STATIC_URL}}js/bootstrap-carousel.js' ></script>
{% endblock %}

{% block content %}
<div style="background-color: rgb(180, 180, 180);">
  <div id="myCarousel" class="carousel slide container" style='width:660px'>
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <!-- Carousel items -->
    <div class="carousel-inner" >
      <div class="active item">
        <img src="{{STATIC_URL}}img/slide1.png" />
      </div>
      <div class="item"><img src="{{STATIC_URL}}img/slide2.png" alt ></div>
      <div class="item"><img src="{{STATIC_URL}}img/slide1.png" alt ></div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</div>
{% endblock %}